on:
    push:
      branches:
        - 5.0
    workflow_dispatch:

jobs:
  deploy-eap-action:
    runs-on: ubuntu-latest
    name: Deploy to the component nexus
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        name: set up jdk 8
        with:
          java-version: 8
      - uses: xstefank/component-deploy-action@main
        with:
          token: ${{ secrets.NEXUS_SECRET_PASSPHRASE }}
          additional-params: -DskipTests
